# Generated by Django 5.2.8 on 2025-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('package_id', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default='confirmed', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
